sudo: true

language: node_js

node_js:
  - "6"
  - "7"
  - "8"
  - "9"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - sudo apt-get update
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++

before_script:
  - npm install -g grunt-cli
